version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: blog-db
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5433:5432"